### ISSUE TITLE
Mixup & Cutmix during Pre-Training

### ISSUE THREAD

**Issue by jizxny** [microsoft/esvit#14]
Hi @ChunyuanLI, I've noticed the usage of mixup and cutmix during pre-training, which is not included in DINO. I'm wondering the performance gain brought by applying mixup & cutmix. Have you ever run any related experiments pre-trained w.o. mixup? I'm especially interested in vanilla DINO with Swin-T/Swin-B as the backbone, i.e., EsViT w. only view-level task, w.o. mixup & cutmix. It would be nice if you could inform me of those results.

**Comment by ChunyuanLI** [comment]
For your request "vanilla DINO with Swin-T/Swin-B as the backbone, i.e., EsViT w. only view-level task, w.o. mixup & cutmix", please see this newly added table in README.md:

<ul style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box;">EsViT with view-level task only</li></ul>

arch | params | tasks | linear | k-nn | download | logs
-- | -- | -- | -- | -- | -- | --
ResNet-50 | 23M | V | 75.0% | 69.1% | full ckpt | train | linear | knn
EsViT (Swin-T, W=7) | 28M | V | 77.0% | 74.2% | full ckpt | train | linear | knn
EsViT (Swin-S, W=7) | 49M | V | 79.2% | 76.9% | full ckpt | train | linear | knn
EsViT (Swin-B, W=7) | 87M | V | 79.6% | 77.7% | full ckpt | train | linear | knn
