### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by madr3z** [microsoft/esvit#2]
What a custom dataset structure should be like and how to train on it?
Let's say I have a dataset of two classes as the folder (binary): 1. Has cat, 2. No cat. In each sub-folder, there are images.
What changes to the code and dataset should I make?
Thanks in advance.

**Comment by ChunyuanLI** [comment]
For pre-training, you don't have to change anything, the default hyper-parameter setting is set to deal with ImageFolders.
